"""Updated user and organisation models

Revision ID: 23a8e50a37ce
Revises: d185120d73e8
Create Date: 2024-07-07 14:38:03.320535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a8e50a37ce'
down_revision = 'd185120d73e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_organisation',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True, primary_kay=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.orgId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['orgId'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['userId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('user_organisation')
    # ### end Alembic commands ###
