"""Updated user and organisation models

Revision ID: ba13a36af18b
Revises: 23a8e50a37ce
Create Date: 2024-07-07 14:49:21.569330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba13a36af18b'
down_revision = '23a8e50a37ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organisation', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organisation', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
